In [91]:
import pandas as pd

In [121]:
# Display all columns
pd.set_option("display.max_columns", None) 
# display all rows
pd.set_option("display.max_rows", None)

In [119]:
path = "/home/marwane/mlops-projects/morocco-appartements-price/moroccan-appartment-price.csv"
df = pd.read_csv(path)
df.shape

(50, 10)

In [120]:
df.columns

Index(['price', 'aire', 'piece', 'rooms', 'bathroom', 'address', 'more_infos',
       'description', 'feat_infos_dic1', 'feat_infos_dic2'],
      dtype='object')

### Dataset description

The data dataset was collected from web site called `mubawab`, I was scraped dat rlate to the appartements, scraping all features of each appartment. SO these dataset is real and it's a this project is very important to any one how want to dive in data scuance and  machine learning.

### Files

### Columns:

* surface: surface of appartment

* piece: number of (bathroom, bedroom, setroom and suisine)

* rooms: number of rooms in the house

* bathroom: number of bathroom in house

* address: address of house whre is located

* more_infos: precise infos about house

* description: explaination of house and it's pieces

* feat_infos_dic1: dictionary of main features

* feat_infos_dic2: dictionary of other features


For the last features that contains a dictionaries as a values needed more preparation to be transform each featurs as a columns, the feature feat_infos_dic1 has a lot of features and each one of them hase labels, for the feat_infos_dic2 contain also a lot features but are binary.

### Target

* price: the price of appartment and it's a target

## Function that transform columns contains dictionaries as values into columns

In [94]:
import ast  # For safely evaluating the string dictionaries


def dict_to_column(df, list_features):
    """ Methode to handle columns with values as a dictionnary"""
    
    list_dataframe = []
    for column in list_features:
        # Create a DataFrame
        #df = pd.DataFrame(df_result)

        # Convert the string representations of dictionaries to actual dictionaries using ast.literal_eval
        df[column] = df[column].apply(ast.literal_eval)

        # Normalize the 'features' column to separate keys into columns
        df_attributes = pd.json_normalize(df[column])

        # Combine the new columns with the original DataFrame
        data = pd.concat([df.drop(columns=[column]), df_attributes], axis=1)
        list_dataframe.append(data) 

    all_df = pd.concat([list_dataframe[0], list_dataframe[1]], axis=1) 

    # remove duplacated columns
    all_df = all_df.loc[~all_df.index.duplicated(),:].copy()
    all_df = all_df.loc[:,~all_df.apply(lambda x: x.duplicated(),axis=1).all()].copy()
    all_df = all_df.drop(["feat_infos_dic1", "feat_infos_dic2"], axis=1)

    return all_df

 
#data = dict_to_column(df, list_features=["feat_infos_dic1", "feat_infos_dic2"])

In [ ]:
df2 = df.copy()

In [96]:
#data.info()

### Features processing

### If the dict is empty do this

In [97]:
"""list_dic = df.feat_infos_dic2.values.tolist()
for i in range(len(list_dic)):
    if list_dic[i] == "{}":
        list_dic[i] = "NaN"

df["feat_infos_dic2"] = list_dic"""

'list_dic = df.feat_infos_dic2.values.tolist()\nfor i in range(len(list_dic)):\n    if list_dic[i] == "{}":\n        list_dic[i] = "NaN"\n\ndf["feat_infos_dic2"] = list_dic'

In [98]:
df2.head(1)

,price,aire,piece,rooms,bathroom,address,more_infos,description,feat_infos_dic1,feat_infos_dic2
0,1 374 000 DH,56 m²,2 Pièces,1 Chambre,1 Salle de bain,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...",{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Climatisation': 'Climatisation', 'Double vit..."

In [99]:
import ast

# The string representation of the dictionary
dict_str = df2["feat_infos_dic1"].values.tolist()#"{'Type de bien\\nAppartement': 'Type de bien\\nAppartement', 'Etat\\nNouveau': 'Etat\\nNouveau', 'Étage du bien\\n1er': 'Étage du bien\\n1er', 'Orientation\\nOuest': 'Orientation\\nOuest', 'Standing\\nHaut standing': 'Standing\\nHaut standing', 'État\\nFinalisé': 'État\\nFinalisé'}"

list_dict1 = []
# Convert the string into a dictionary
for i in range(len(dict_str)):
    dict_obj = ast.literal_eval(dict_str[i])
    list_dict1.append(dict_obj)


dict_str = df2["feat_infos_dic2"].values.tolist()#"{'Type de bien\\nAppartement': 'Type de bien\\nAppartement', 'Etat\\nNouveau': 'Etat\\nNouveau', 'Étage du bien\\n1er': 'Étage du bien\\n1er', 'Orientation\\nOuest': 'Orientation\\nOuest', 'Standing\\nHaut standing': 'Standing\\nHaut standing', 'État\\nFinalisé': 'État\\nFinalisé'}"

list_dict2 = []
# Convert the string into a dictionary
for i in range(len(dict_str)):
    dict_obj = ast.literal_eval(dict_str[i])
    list_dict2.append(dict_obj)
#for i in range(len(list_dict)):
    #key = list_dict[i].keys()
    #print(key)

In [100]:
df_dict2 = df2["feat_infos_dic2"].copy()
df_dict2

0     {'Climatisation': 'Climatisation', 'Double vit...
1     {'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense...
2                                                    {}
3                            {'Ascenseur': 'Ascenseur'}
4     {'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri...
5                                                    {}
6     {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
7        {'Terrasse': 'Terrasse', 'Piscine': 'Piscine'}
8     {'Climatisation': 'Climatisation', 'Sécurité':...
9     {'Ascenseur': 'Ascenseur', 'Climatisation': 'C...
10                                                   {}
11    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
12                           {'Ascenseur': 'Ascenseur'}
13    {'Piscine': 'Piscine', 'Concierge': 'Concierge...
14    {'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense...
15    {'Garage': 'Garage', 'Ascenseur': 'Ascenseur',...
16                                                   {}
17                           {'Ascenseur': 'Ascenseur'}
18    {'Climatisation': 'Climatisation', 'Sécurité':...
19    {'Climatisation': 'Climatisation', 'Double vit...
20                           {'Ascenseur': 'Ascenseur'}
21                           {'Ascenseur': 'Ascenseur'}
22    {'Garage': 'Garage', 'Ascenseur': 'Ascenseur',...
23    {'Jardin': 'Jardin', 'Terrasse': 'Terrasse', '...
24    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
25    {'Climatisation': 'Climatisation', 'Sécurité':...
26    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
27    {'Terrasse': 'Terrasse', 'Salon Marocain': 'Sa...
28    {'Garage': 'Garage', 'Ascenseur': 'Ascenseur',...
29    {'Ascenseur': 'Ascenseur', 'Concierge': 'Conci...
30    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
31    {'Jardin': 'Jardin', 'Terrasse': 'Terrasse', '...
32    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
33    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
34    {'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri...
35                                                   {}
36         {'Garage': 'Garage', 'Sécurité': 'Sécurité'}
37                           {'Ascenseur': 'Ascenseur'}
38    {'Climatisation': 'Climatisation', 'Sécurité':...
39                           {'Ascenseur': 'Ascenseur'}
40                           {'Ascenseur': 'Ascenseur'}
41                           {'Ascenseur': 'Ascenseur'}
42                           {'Ascenseur': 'Ascenseur'}
43       {'Terrasse': 'Terrasse', 'Piscine': 'Piscine'}
44                           {'Ascenseur': 'Ascenseur'}
45    {'Garage': 'Garage', 'Ascenseur': 'Ascenseur',...
46                           {'Ascenseur': 'Ascenseur'}
47    {'Terrasse': 'Terrasse', 'Garage': 'Garage', '...
48    {'Climatisation': 'Climatisation', 'Sécurité':...
49                                                   {}
Name: feat_infos_dic2, dtype: object

In [101]:
"""# Function to clean the keys (remove text after \n)
def clean_key(key, value):
    return key.split('\n')[0], value.split("\n")[1]

clean_key('Type de bien\nAppartement','Type de bien\nA')[0]"""

'# Function to clean the keys (remove text after \n)\ndef clean_key(key, value):\n    return key.split(\'\n\')[0], value.split("\n")[1]\n\nclean_key(\'Type de bien\nAppartement\',\'Type de bien\nA\')[0]'

In [124]:
 
# Function to clean the keys (remove text after \n)
def clean_key(key, value=None):
    
    return key.split('\n')[0], value.split("\n")[1]
    
    
# Apply the clean_key function to each dictionary's keys
cleaned_dict_list1 = [{clean_key(k, v)[0]: clean_key(k, v)[1] for k, v in zip(d.keys(), d.values())} for d in list_dict1]

# Extract the cleaned keys from each dictionary
df2['dict1'] = cleaned_dict_list1 
 
# Extract the cleaned keys from each dictionary
df2['dict2'] = list_dict2 
 
df2.head()

,price,aire,piece,rooms,bathroom,address,more_infos,description,feat_infos_dic1,feat_infos_dic2,dict1,dict2
0,1 374 000 DH,56 m²,2 Pièces,1 Chambre,1 Salle de bain,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...",{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Climatisation': 'Climatisation', 'Double vit...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...","{'Climatisation': 'Climatisation', 'Double vit..."
1,1 872 600 DH,104 m²,4 Pièces,3 Chambres,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...",{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...","{'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense..."
2,1 394 500 DH,116 m²,2 Chambres,1 Salle de bain,NaN,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. Surface t...,"Avec sa situation privilégiée, à proximité du ...",{'Type de bien\nAppartement': 'Type de bien\nA...,{},"{'Type de bien': 'Appartement', 'État': 'Final...",{}
3,1 674 000 DH,136 m²,3 Pièces,2 Chambres,1 Salle de bain,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. 2 belles ...,Faites une belle affaire en achetant cet appar...,{'Type de bien\nAppartement': 'Type de bien\nA...,{'Ascenseur': 'Ascenseur'},"{'Type de bien': 'Appartement', 'Etat': 'Nouve...",{'Ascenseur': 'Ascenseur'}
4,894 400 DH,71 m²,4 Pièces,2 Chambres,2 Salles de bains,Aïn Sebaâ à Casablanca,Bel appartement à vendre à Ain Sebaa,Charmant appartement de 96 m² composé de 3 cha...,{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...","{'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri..."

In [ ]:
import ast  # For safely evaluating the string dictionaries


def to_string(value):
    return str(value) 

def dict_to_column(df, list_features):
    """ Methode to handle columns with values as a dictionnary """
       
    list_dataframe = []
    for column in list_features: 
        
        #Convert dict to string
        df2[column]= df2[column].apply(to_string)
        # Convert the string representations of dictionaries to actual dictionaries using ast.literal_eval
        df[column] = df[column].apply(ast.literal_eval)

        # Normalize the 'features' column to separate keys into columns
        df_attributes = pd.json_normalize(df[column])

        # Combine the new columns with the original DataFrame
        data = pd.concat([df.drop(columns=[column]), df_attributes], axis=1)
        list_dataframe.append(data) 

    all_df = pd.concat([list_dataframe[0], list_dataframe[1]], axis=1) 

    # remove duplacated columns
    all_df = all_df.loc[~all_df.index.duplicated(),:].copy()
    all_df = all_df.loc[:,~all_df.apply(lambda x: x.duplicated(),axis=1).all()].copy()
    all_df = all_df.drop(["feat_infos_dic1", "feat_infos_dic2"], axis=1)

    return all_df

 
data = dict_to_column(df2, list_features=["dict2", "dict1"])

data.head(2)

,price,aire,piece,rooms,bathroom,address,more_infos,description,dict1,Climatisation,Double vitrage,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,Garage,Piscine,Façade extérieure,Salon Marocain,Chambre rangement,Salon européen,Antenne parabolique,Porte blindée,Jardin,Cheminée,Meublé,Réfrigérateur,Machine à laver,Chauffage central,dict2,Type de bien,Etat,Étage du bien,Orientation,Standing,État,Etat du bien,Type du sol,Livraison:,Surface extérieure
0,1 374 000 DH,56 m²,2 Pièces,1 Chambre,1 Salle de bain,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...",Climatisation,Double vitrage,Cuisine équipée,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Climatisation': 'Climatisation', 'Double vit...",Appartement,Nouveau,1er,Ouest,Haut standing,Finalisé,NaN,NaN,NaN,NaN
1,1 872 600 DH,104 m²,4 Pièces,3 Chambres,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...",Climatisation,NaN,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense...",Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN

### To binary data (0 & 1)

In [126]:

data_dict2 = data[['Climatisation', 'Double vitrage', 'Cuisine équipée', 'Terrasse', 'Ascenseur', 'Concierge', 'Sécurité',
       'Four', 'Garage', 'Piscine', 'Façade extérieure', 'Salon Marocain', 'Chambre rangement', 'Salon européen', 'Antenne parabolique',
       'Porte blindée', 'Jardin', 'Cheminée', 'Meublé', 'Réfrigérateur', 'Machine à laver', 'Chauffage central']]

In [127]:
def to_binary(column_name):
    #values = data[column_name].values.tolist()
    if column_name==column_name:
        return 1
    else:
        return 0

In [129]:
for column_name in data_dict2.columns:
    data_dict2.loc[:,column_name] = data_dict2[column_name].apply(to_binary)
 
data_dict2.head()

,Climatisation,Double vitrage,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,Garage,Piscine,Façade extérieure,Salon Marocain,Chambre rangement,Salon européen,Antenne parabolique,Porte blindée,Jardin,Cheminée,Meublé,Réfrigérateur,Machine à laver,Chauffage central
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [130]:
data["Jardin"].value_counts()

Jardin
Jardin    2
Name: count, dtype: int64

In [107]:
data_dict2["Jardin"].value_counts()#.sum()

Jardin
0    48
1     2
Name: count, dtype: int64

In [108]:
data.shape

(50, 42)

### Check if the given in th text

In [131]:
def check_term_in_text(word):
    list_values = []
    for i in range(50):
        if word in data.more_infos.values.tolist()[i]:
            list_values.append(word)
        else:
            list_values.append("NaN")
    return list_values

In [132]:
check_term_in_text(word="parking")

['NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'parking',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'parking',
 'NaN',
 'NaN',
 'NaN',
 'NaN']

In [133]:
data.isna().sum()

price                   0
aire                    0
piece                   0
rooms                   0
bathroom               11
address                 0
more_infos              0
description             2
dict1                   0
Climatisation          34
Double vitrage         45
Cuisine équipée        31
Terrasse               35
Ascenseur              19
Concierge              36
Sécurité               36
Four                   37
Garage                 36
Piscine                47
Façade extérieure      45
Salon Marocain         41
Chambre rangement      47
Salon européen         42
Antenne parabolique    45
Porte blindée          48
Jardin                 48
Cheminée               47
Meublé                 48
Réfrigérateur          49
Machine à laver        49
Chauffage central      49
dict2                   0
Type de bien            0
Etat                    8
Étage du bien          37
Orientation            39
Standing               17
État                   12
Etat du bien           36
Type du sol            36
Livraison:             37
Surface extérieure     49
dtype: int64

In [134]:
data=data.rename(columns={"aire": "surface"})
data.head(2)

,price,surface,piece,rooms,bathroom,address,more_infos,description,dict1,Climatisation,Double vitrage,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,Garage,Piscine,Façade extérieure,Salon Marocain,Chambre rangement,Salon européen,Antenne parabolique,Porte blindée,Jardin,Cheminée,Meublé,Réfrigérateur,Machine à laver,Chauffage central,dict2,Type de bien,Etat,Étage du bien,Orientation,Standing,État,Etat du bien,Type du sol,Livraison:,Surface extérieure
0,1 374 000 DH,56 m²,2 Pièces,1 Chambre,1 Salle de bain,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...",Climatisation,Double vitrage,Cuisine équipée,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Climatisation': 'Climatisation', 'Double vit...",Appartement,Nouveau,1er,Ouest,Haut standing,Finalisé,NaN,NaN,NaN,NaN
1,1 872 600 DH,104 m²,4 Pièces,3 Chambres,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...",Climatisation,NaN,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense...",Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN

In [135]:
data.columns
data_dict1 = data[['Type de bien', 'Etat','Étage du bien', 'Orientation', 'Standing', 'État', 'Etat du bien', 'Type du sol', 'Livraison:', 'Surface extérieure']]

for column_name in data_dict1.columns:
       print(data_dict1[column_name].value_counts())

Type de bien
Appartement    50
Name: count, dtype: int64
Etat
Nouveau      32
Bon état      9
À rénover     1
Name: count, dtype: int64
Étage du bien
1er     4
3ème    3
4ème    3
2ème    2
5ème    1
Name: count, dtype: int64
Orientation
Sud      6
Ouest    3
Est      1
Nord     1
Name: count, dtype: int64
Standing
Haut standing     26
Moyen standing     7
Name: count, dtype: int64
État
Finalisé                    31
En cours de construction     7
Name: count, dtype: int64
Etat du bien
10-20 ans        6
Moins d'un an    4
20-30 ans        3
1-5 ans          1
Name: count, dtype: int64
Type du sol
Marbre       8
Carrelage    6
Name: count, dtype: int64
Livraison:
décembre 2025     2
juillet 2024      2
juin 2024         2
décembre 2023     1
juin 2023         1
janvier 2024      1
août 2024         1
juin 2025         1
septembre 2024    1
novembre 2024     1
Name: count, dtype: int64
Surface extérieure
20 m²    1
Name: count, dtype: int64

In [136]:
df1 = pd.concat([data.iloc[:, :8], data_dict1, data_dict2], axis=1)
df1.head(2)

,price,surface,piece,rooms,bathroom,address,more_infos,description,Type de bien,Etat,Étage du bien,Orientation,Standing,État,Etat du bien,Type du sol,Livraison:,Surface extérieure,Climatisation,Double vitrage,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,Garage,Piscine,Façade extérieure,Salon Marocain,Chambre rangement,Salon européen,Antenne parabolique,Porte blindée,Jardin,Cheminée,Meublé,Réfrigérateur,Machine à laver,Chauffage central
0,1 374 000 DH,56 m²,2 Pièces,1 Chambre,1 Salle de bain,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...",Appartement,Nouveau,1er,Ouest,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1 872 600 DH,104 m²,4 Pièces,3 Chambres,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...",Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [137]:
df1.shape

(50, 40)

## Clean dataset

In [138]:
import re 


def clean_column(value):
    try:
        value = re.sub("[^0-9]","", value)#.replace("DH", "")
    except:
        value = "NaN"
    return value

df1["price"] = df1["price"].apply(clean_column)
df1["piece"] = df1["piece"].apply(clean_column)
df1["rooms"] = df1["rooms"].apply(clean_column)
df1["bathroom"] = df1["bathroom"].apply(clean_column) 
df1["surface"] = df1["surface"].apply(clean_column)   

df1.head(2)

,price,surface,piece,rooms,bathroom,address,more_infos,description,Type de bien,Etat,Étage du bien,Orientation,Standing,État,Etat du bien,Type du sol,Livraison:,Surface extérieure,Climatisation,Double vitrage,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,Garage,Piscine,Façade extérieure,Salon Marocain,Chambre rangement,Salon européen,Antenne parabolique,Porte blindée,Jardin,Cheminée,Meublé,Réfrigérateur,Machine à laver,Chauffage central
0,1374000,56,2,1,1,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...",Appartement,Nouveau,1er,Ouest,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1872600,104,4,3,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...",Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [141]:


# format features
new_colums_name = [string.lower().replace(" ", "_") for string in df1.columns.to_list()]
dic_ond_new_features = {}
for old_name, new_name in zip(df1.columns, new_colums_name):
    dic_ond_new_features.update({old_name: new_name})


df1["étage_du_bien"] = df1["étage_du_bien"].apply(clean_column)

df1 = df1.rename(columns=dic_ond_new_features) 
df1.head()

,price,surface,piece,rooms,bathroom,address,more_infos,description,type_de_bien,etat,étage_du_bien,orientation,standing,état,etat_du_bien,type_du_sol,livraison:,surface_extérieure,climatisation,double_vitrage,cuisine_équipée,terrasse,ascenseur,concierge,sécurité,four,garage,piscine,façade_extérieure,salon_marocain,chambre_rangement,salon_européen,antenne_parabolique,porte_blindée,jardin,cheminée,meublé,réfrigérateur,machine_à_laver,chauffage_central
0,1374000,56,2,1,1,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...",Appartement,Nouveau,1,Ouest,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1872600,104,4,3,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...",Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,1394500,116,2,1,NaN,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. Surface t...,"Avec sa situation privilégiée, à proximité du ...",Appartement,NaN,NaN,NaN,NaN,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,1674000,136,3,2,1,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. 2 belles ...,Faites une belle affaire en achetant cet appar...,Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,894400,71,4,2,2,Aïn Sebaâ à Casablanca,Bel appartement à vendre à Ain Sebaa,Charmant appartement de 96 m² composé de 3 cha...,Appartement,Nouveau,NaN,NaN,Moyen standing,Finalisé,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [143]:
df1.to_csv("moroccan-houses-price-data.csv", index=False)

In [ ]:
"""
# format features
new_colums_name = [string.lower().replace(" ", "_") for string in data.columns.to_list()]
dic_ond_new_features = {}
for old_name, new_name in zip(data.columns, new_colums_name):
    dic_ond_new_features.update({old_name: new_name})

data = data.rename(columns=dic_ond_new_features) 
data.head()"""

,price,surface,piece,rooms,bathroom,address,more_infos,description,dict1,climatisation,double_vitrage,cuisine_équipée,terrasse,ascenseur,concierge,sécurité,four,garage,piscine,façade_extérieure,salon_marocain,chambre_rangement,salon_européen,antenne_parabolique,porte_blindée,jardin,cheminée,meublé,réfrigérateur,machine_à_laver,chauffage_central,dict2,type_de_bien,etat,étage_du_bien,orientation,standing,état,etat_du_bien,type_du_sol,livraison:,surface_extérieure
0,1 374 000 DH,56 m²,2 Pièces,1 Chambre,1 Salle de bain,Riviera à Casablanca,Beau studio à vendre Riviera,"Que vous soyez jeune actif, investisseur ou si...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...",Climatisation,Double vitrage,Cuisine équipée,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Climatisation': 'Climatisation', 'Double vit...",Appartement,Nouveau,1er,Ouest,Haut standing,Finalisé,NaN,NaN,NaN,NaN
1,1 872 600 DH,104 m²,4 Pièces,3 Chambres,NaN,Californie à Casablanca,Magnifique appartement à vendre à Californie,"Les Allées de Californie 2, plus qu’une simple...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...",Climatisation,NaN,Cuisine équipée,Terrasse,Ascenseur,Concierge,Sécurité,Four,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Terrasse': 'Terrasse', 'Ascenseur': 'Ascense...",Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN
2,1 394 500 DH,116 m²,2 Chambres,1 Salle de bain,NaN,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. Surface t...,"Avec sa situation privilégiée, à proximité du ...","{'Type de bien': 'Appartement', 'État': 'Final...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{},Appartement,NaN,NaN,NaN,NaN,Finalisé,NaN,NaN,NaN,NaN
3,1 674 000 DH,136 m²,3 Pièces,2 Chambres,1 Salle de bain,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. 2 belles ...,Faites une belle affaire en achetant cet appar...,"{'Type de bien': 'Appartement', 'Etat': 'Nouve...",NaN,NaN,NaN,NaN,Ascenseur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'Ascenseur': 'Ascenseur'},Appartement,Nouveau,NaN,NaN,Haut standing,Finalisé,NaN,NaN,NaN,NaN
4,894 400 DH,71 m²,4 Pièces,2 Chambres,2 Salles de bains,Aïn Sebaâ à Casablanca,Bel appartement à vendre à Ain Sebaa,Charmant appartement de 96 m² composé de 3 cha...,"{'Type de bien': 'Appartement', 'Etat': 'Nouve...",NaN,NaN,Cuisine équipée,NaN,Ascenseur,NaN,Sécurité,Four,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri...",Appartement,Nouveau,NaN,NaN,Moyen standing,Finalisé,NaN,NaN,NaN,NaN