In [71]:

import pandas as pd
#data = pd.read_csv("data/moroccan-houce-price-1.csv")
data = pd.read_csv("/home/marwane/mlops-projects/morocco-appartements-price/dataset/moroccan-houce-price-1.csv")

In [72]:
df = data.copy()
df.shape

(100, 9)

In [73]:
df.head()

,price,surface,piece,rooms,bathroom,address,description,more_features_1_dict,more_features_2_dict
0,1 062 700 DH,112 m²,3 Pièces,2 Chambres,1 Salle de bain,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. 2 chambre...,{'Type de bien\nAppartement': 'Type de bien\nA...,{}
1,913 100 DH,60 m²,1 Salle de bain,NaN,NaN,Hay Hassani à Casablanca,Plateau bureau à vendre en plein quartier Hay ...,{'Type de bien\nBureau': 'Type de bien\nBureau...,{}
2,894 400 DH,71 m²,3 Pièces,2 Chambres,2 Salles de bains,Aïn Sebaâ à Casablanca,Très bel appartement à vendre à Ain Sebaa\nCha...,{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri..."
3,45 000 000 DH,2500 m²,7 Pièces,5 Chambres,4 Salles de bains,Anfa Supérieur à Casablanca,Villa à démolir à vendre sur Anfa Supérieur\nV...,"{'Type de bien\nVilla': 'Type de bien\nVilla',...","{'Jardin': 'Jardin', 'Terrasse': 'Terrasse', '..."
4,2 700 000 DH,176 m²,5 Pièces,3 Chambres,3 Salles de bains,Mers Sultan à Casablanca,Un Magnifique Appartement a vendre sur Casabla...,{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Jardin': 'Jardin', 'Terrasse': 'Terrasse', '..."

In [64]:
import ast

 
"""
list_features_main1 = df.features_dict.values.tolist()
list_dict = []
# Convert the string into a dictionary
for i in range(len(list_features_main1)):
    value = list_features_main1[i]
    dict_obj = ast.literal_eval(value)
    list_dict.append(dict_obj)
"""

list_more_features_main_1 = df["more_features_1_dict"].values.tolist()#"{'Type de bien\\nAppartement': 'Type de bien\\nAppartement', 'Etat\\nNouveau': 'Etat\\nNouveau', 'Étage du bien\\n1er': 'Étage du bien\\n1er', 'Orientation\\nOuest': 'Orientation\\nOuest', 'Standing\\nHaut standing': 'Standing\\nHaut standing', 'État\\nFinalisé': 'État\\nFinalisé'}"
list_dict1 = []
# Convert the string into a dictionary
for i in range(len(list_more_features_main_1)):
    dict_obj = ast.literal_eval(list_more_features_main_1[i])
    list_dict1.append(dict_obj)


list_more_features = df["more_features_2_dict"].values.tolist()#"{'Type de bien\\nAppartement': 'Type de bien\\nAppartement', 'Etat\\nNouveau': 'Etat\\nNouveau', 'Étage du bien\\n1er': 'Étage du bien\\n1er', 'Orientation\\nOuest': 'Orientation\\nOuest', 'Standing\\nHaut standing': 'Standing\\nHaut standing', 'État\\nFinalisé': 'État\\nFinalisé'}"
list_dict2 = []
# Convert the string into a dictionary
for i in range(len(list_more_features)):
    dict_obj = ast.literal_eval(list_more_features[i])
    list_dict2.append(dict_obj)

In [65]:
 # Function to clean the keys (remove text after \n)
def clean_key(key, value=None):
    
    return key.split('\n')[0], value.split("\n")[1]
    
df2 = df.copy()
# Apply the clean_key function to each dictionary's keys
cleaned_dict_list1 = [{clean_key(k, v)[0]: clean_key(k, v)[1] for k, v in zip(d.keys(), d.values())} for d in list_dict1]

# Extract the cleaned keys from each dictionary
df2['dict1'] = cleaned_dict_list1 
 
# Extract the cleaned keys from each dictionary
df2['dict2'] = list_more_features 
 
df2.head()

,price,surface,piece,rooms,bathroom,address,description,more_features_1_dict,more_features_2_dict,dict1,dict2
0,1 062 700 DH,112 m²,3 Pièces,2 Chambres,1 Salle de bain,Sidi Maarouf à Casablanca,Appartement à vendre à Sidi Maarouf. 2 chambre...,{'Type de bien\nAppartement': 'Type de bien\nA...,{},"{'Type de bien': 'Appartement', 'Etat': 'Nouve...",{}
1,913 100 DH,60 m²,1 Salle de bain,NaN,NaN,Hay Hassani à Casablanca,Plateau bureau à vendre en plein quartier Hay ...,{'Type de bien\nBureau': 'Type de bien\nBureau...,{},"{'Type de bien': 'Bureau', 'Etat': 'Nouveau', ...",{}
2,894 400 DH,71 m²,3 Pièces,2 Chambres,2 Salles de bains,Aïn Sebaâ à Casablanca,Très bel appartement à vendre à Ain Sebaa\nCha...,{'Type de bien\nAppartement': 'Type de bien\nA...,"{'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri...","{'Type de bien': 'Appartement', 'Etat': 'Nouve...","{'Ascenseur': 'Ascenseur', 'Sécurité': 'Sécuri..."

In [66]:
df2.dict1.values.tolist()[0]

{'Type de bien': 'Appartement', 'Etat': 'Nouveau', 'État': 'Finalisé'}

In [70]:
import ast  # For safely evaluating the string dictionaries


def dict_to_column(df, list_features):
    """ Methode to handle columns with values as a dictionnary"""
    
    list_dataframe = []
    for column in list_features:
        # Create a DataFrame
        #df = pd.DataFrame(df_result)

        # Convert the string representations of dictionaries to actual dictionaries using ast.literal_eval
        df[column] = df[column].apply(ast.literal_eval)

        # Normalize the 'features' column to separate keys into columns
        df_attributes = pd.json_normalize(df[column])

        # Combine the new columns with the original DataFrame
        data = pd.concat([df.drop(columns=[column]), df_attributes], axis=1)
        list_dataframe.append(data) 

    all_df = pd.concat([list_dataframe[0], list_dataframe[1]], axis=1) 

    # remove duplacated columns
    all_df = all_df.loc[~all_df.index.duplicated(),:].copy()
    all_df = all_df.loc[:,~all_df.apply(lambda x: x.duplicated(),axis=1).all()].copy()
    #all_df = all_df.drop(["dict1", "dict2"], axis=1)

    return all_df

 
data = dict_to_column(df=df2, list_features=["dict1"])

ValueError: malformed node or string: {'Type de bien': 'Appartement', 'Etat': 'Nouveau', 'État': 'Finalisé'}

In [ ]:
import pandas as pd
import ast

def sanitize_dict_string(dict_string):
    """Function to sanitize the dictionary string."""
    # Ensure proper formatting for single quotes and other potential issues
    dict_string = dict_string.replace("’", "'")  # Replace curly quotes with regular ones
    dict_string = dict_string.replace('“', '"').replace('”', '"')  # Replace curly quotes with standard ones
    return dict_string

def dict_to_column(df, list_features):
    """ Method to handle columns with values as a dictionary."""
    
    list_dataframe = []
    
    for column in list_features:
        # Apply the sanitization and conversion process to the dictionary string
        df[column] = df[column].apply(lambda x: sanitize_dict_string(x))  # Clean the string

        # Convert the sanitized string representations of dictionaries to actual dictionaries
        try:
            df[column] = df[column].apply(ast.literal_eval)
        except ValueError as e:
            print(f"Error converting column '{column}' to dictionary: {e}")
            df[column] = None  # Set as None or handle according to your need

        # Normalize the dictionary column into separate columns
        df_attributes = pd.json_normalize(df[column])

        # Combine the new columns with the original DataFrame
        data = pd.concat([df.drop(columns=[column]), df_attributes], axis=1)
        list_dataframe.append(data)

    # Concatenate all DataFrames from the list
    all_df = pd.concat(list_dataframe, axis=1) 

    # Remove duplicated columns and rows
    all_df = all_df.loc[~all_df.index.duplicated(), :].copy()
    all_df = all_df.loc[:, ~all_df.apply(lambda x: x.duplicated(), axis=1).all()].copy()

    return all_df

# Example usage (assuming you have the dataframe 'df' and list of columns 'list_features')
# df = dict_to_column(df, list_features=["feat_infos_dic1", "feat_infos_dic2"])

In [ ]:
dd = dict_to_column(df=df2, list_features=["dict1", "dict2"])

In [ ]:
import json

data1 = '{"Type de bien": "Appartement", "Etat": "Nouveau", "État": "Finalisé"}'
try:
    dictionary = json.loads(data1)
    print(dictionary)
except json.JSONDecodeError as e:
    print(f"Error parsing JSON: {e}")

In [ ]:
{'Type de bien': 'Appartement', 'Etat': 'Nouveau', 'État': 'Finalisé'}

In [ ]:
 
# Function to clean the keys (remove text after \n)
def clean_key(key, value=None): 
    return key.split('\n')[0], value.split("\n")[1]
    
    
# Apply the clean_key function to each dictionary's keys
cleaned_list_dict2 = [{clean_key(k, v)[0]: clean_key(k, v)[1] for k, v in zip(d.keys(), d.values())} for d in list_dict2]

# Extract the cleaned keys from each dictionary
#df['dict1'] = list_dict 
df.insert(1, "dict1", list_dict)

# Extract the cleaned keys from each dictionary
#df['dict2'] = cleaned_list_dict2 
df.insert(5, "dict2", cleaned_list_dict2)

# Extract the cleaned keys from each dictionary
#df['dict3'] = list_dict3
df.insert(7, "dict3", list_dict3)
 
df.head()

In [ ]:
x = 'm²'
x[-2:  ]

In [ ]:
import ast  # For safely evaluating the string dictionaries


def to_string(value):
    return str(value) 

def dict_to_column(df, list_features):
    """ Methode to handle columns with values as a dictionnary """
       
    list_dataframe = []
    for column in list_features: 
        
        #Convert dict to string
        df[column]= df[column].apply(to_string)
        # Convert the string representations of dictionaries to actual dictionaries using ast.literal_eval
        df[column] = df[column].apply(ast.literal_eval)

        # Normalize the 'features' column to separate keys into columns
        df_attributes = pd.json_normalize(df[column])

        # Combine the new columns with the original DataFrame
        data = pd.concat([df.drop(columns=[column]), df_attributes], axis=1)
        list_dataframe.append(data) 

    all_df = pd.concat([list_dataframe[0], list_dataframe[1]], axis=1) 

    # remove duplacated columns
    all_df = all_df.loc[~all_df.index.duplicated(),:].copy()
    all_df = all_df.loc[:,~all_df.apply(lambda x: x.duplicated(),axis=1).all()].copy()
    #all_df = all_df.drop(["feat_infos_dic1", "feat_infos_dic2"], axis=1)
    return all_df
    
 
data = dict_to_column(df=df, list_features=["dict2", "dict3"])

data.head(2)

In [ ]:
import pandas as pd
import ast
import re

# Original list of strings representing dictionaries
data = [
    "{'112 m²': '112 m²', '3 Pièces': '3 Pièces', '2 Chambres': '2 Chambres', '1 Salle de bain': '1 Salle de bain'}",
    "{'60 m²': '60 m²', '1 Salle de bain': '1 Salle de bain'}",
    "{'71 m²': '71 m²', '3 Pièces': '3 Pièces', '2 Chambres': '2 Chambres', '2 Salles de bains': '2 Salles de bains'}"
]

# Convert the string representations to dictionaries
dicts = [ast.literal_eval(item) for item in data]

# Function to remove numbers from keys
def remove_numbers_from_key(key):
    return re.sub(r'\d+', '', key)

# Update the keys in each dictionary
updated_dicts = [{remove_numbers_from_key(k): v for k, v in d.items()} for d in dicts]

# Convert the updated list of dictionaries into a pandas DataFrame
df = pd.DataFrame(updated_dicts)

# Display the DataFrame
print(df)